# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_CPU_COUNT = "2"
BOX_RAM_MB = "2048"

#
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "lab-4"
    vb.memory = BOX_RAM_MB
    vb.cpus = BOX_CPU_COUNT
  end
 
end
