# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_CPU_COUNT = "1"
BOX_RAM_MB = "1024"
IP_ADDRESS = { web1: "192.168.56.11", web2: "192.168.56.12" }


Vagrant.configure("2") do |config|

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: IP_ADDRESS[:web1]
    web1.vm.provision "shell" do |s|
      s.path = "script.sh"
      s.args = "1"
    end
    web1.vm.provider "virtualbox" do |v|
      v.memory = BOX_RAM_MB
      v.cpus = BOX_CPU_COUNT
    end
  end
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/xenial64"
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: IP_ADDRESS[:web2]
    web2.vm.provision "shell" do |s|
      s.path = "script.sh"
      s.args = "2"
    end
    web2.vm.provider "virtualbox" do |v|
      v.memory = BOX_RAM_MB
      v.cpus = BOX_CPU_COUNT
    end
  end
end
