# -*- mode: ruby -*-
# vi: set ft=ruby :

IP_ADDRESS = "192.168.56.10"
BOX_CPU_COUNT = 1
BOX_RAM_MB = 1024

Vagrant.configure("2") do |config|
  config.vm.box = "mahdou/nginx"
  config.vm.hostname = "nginx"
  config.vm.box_version = "1.0"
  config.vm.network "private_network", ip: IP_ADDRESS
  config.vm.synced_folder "template_w3schools", "/usr/share/nginx/html/"
  config.vm.provider "virtualbox" do |v|
    v.memory = BOX_RAM_MB
    v.cpus = BOX_CPU_COUNT
  end
end
