# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_RAM_MB = "2048"
BOX_CPU_COUNT = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |v|
    v.memory = BOX_RAM_MB
    v.cpus = BOX_CPU_COUNT
    v.name = "my_vm"
    v.gui = true
  end
end
